### PR TITLE
Create directory of `pocket-lib-token-file` if it doesn't exist

### PR DESCRIPTION
**Pull request by kevinjfoley**
`with-temp-file` throws error if the directory of the file doesn't exist

### CODE REVIEW

**Comment by alphapapa** [comment]
Hi,

Thanks for submitting this.

I think I'd prefer to handle this by alerting the user that they should either create the directory or configure a different location for the token file.  In this case, if the `~/.cache` directory doesn't exist, they're probably on a platform that doesn't use that directory, so creating it might not be the best thing to do.

What do you think?

**Comment by kevinjfoley** [comment]
No problem, thanks for all of your work on your packages.

Yeah I think you're right, it's probably safer to alert the user and have the create the `.cache` directory or change `pocket-lib-token-file`.

I'll also add some details to the README.

**Comment by kevinjfoley** [comment]
Added a user error if the directory doesn't exist and some info to the README.  Please feel free to change however you see fit or scrap entirely and implement another way.

**Comment by alphapapa** [comment]
Thanks, I'll give it a little thought and check back soon.

**Comment by alphapapa** [comment]
Well, "soon" wasn't very soon, after all.  :)  It occurs to me, we should probably test it with `file-writable-p` instead of `file-directory-p`.  What do you think?  (If you still care about this, haha.)  Thanks.

**Comment by kevinjfoley** [comment]
You're right, `file-writable-p` makes more sense here, I've pushed the change.  I no longer use pocket but hopefully this saves another user some confusion =)

**Comment by alphapapa** [comment]
Hi Kevin,

Apologies for the long delay.  Feel free to ping me in the future in case I forget something like this.  Thank you for contributing this fix.

**Pull request merged**
